-- Core knowledge layer for theprolificpoppin.com
-- Designed for future essay search, retrieval-augmented generation, and discussion flows.

create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists essays (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null,
  category text not null default 'the-ache',
  published boolean not null default false,
  featured boolean not null default false,
  read_time integer not null default 0,
  source_path text,
  source_revision text,
  source_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists essays_category_idx on essays (category);
create index if not exists essays_published_idx on essays (published);

create table if not exists essay_chunks (
  id bigint generated by default as identity primary key,
  essay_id bigint not null references essays(id) on delete cascade,
  chunk_order integer not null,
  kind text not null default 'paragraph',
  heading text,
  content text not null,
  token_count integer not null default 0,
  embedding vector(1536),
  embedding_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (essay_id, chunk_order)
);

create index if not exists essay_chunks_essay_id_idx on essay_chunks (essay_id);
create index if not exists essay_chunks_kind_idx on essay_chunks (kind);

create table if not exists site_pages (
  page_key text primary key,
  title text not null,
  content text not null,
  updated_at timestamptz not null default now()
);

create table if not exists featured_essays (
  position integer primary key check (position between 1 and 4),
  essay_id bigint not null references essays(id) on delete cascade unique
);

-- Future discussion threads grounded in essay knowledge.
create table if not exists ai_discussion_threads (
  id uuid primary key default gen_random_uuid(),
  essay_id bigint references essays(id) on delete set null,
  thread_title text,
  user_prompt text not null,
  assistant_summary text,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_discussion_threads_essay_id_idx on ai_discussion_threads (essay_id);
create index if not exists ai_discussion_threads_status_idx on ai_discussion_threads (status);

create table if not exists ai_discussion_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references ai_discussion_threads(id) on delete cascade,
  role text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_discussion_messages_thread_id_idx on ai_discussion_messages (thread_id);
create index if not exists ai_discussion_messages_role_idx on ai_discussion_messages (role);

-- Future supervised / fine-tuning style records derived from essay + discussion data.
create table if not exists ai_training_examples (
  id uuid primary key default gen_random_uuid(),
  essay_id bigint references essays(id) on delete set null,
  source_type text not null default 'essay',
  prompt text not null,
  completion text not null,
  labels jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_training_examples_essay_id_idx on ai_training_examples (essay_id);
create index if not exists ai_training_examples_source_type_idx on ai_training_examples (source_type);

create or replace view essay_knowledge_documents as
select
  e.id as essay_id,
  e.slug,
  e.title,
  e.category,
  e.published,
  e.featured,
  c.id as chunk_id,
  c.chunk_order,
  c.kind,
  c.heading,
  c.content,
  c.embedding_model
from essays e
left join essay_chunks c on c.essay_id = e.id;
